INSTRUCTION = {
    "en": "Note: Please put the final answer in the $\\boxed{}$.",
    "de": "Hinweis: Bitte setzen Sie die endgültige Antwort in $\\boxed{}$.",
    "es": "Nota: Por favor, coloque la respuesta final en $\\boxed{}$.",
    "ru": "Примечание: Пожалуйста, поместите окончательный ответ в $\boxed{}$.",
    "hi": "नोट: कृपया अंतिम उत्तर को $\\boxed{}$ में रखें।",
    "tr": "Not: Lütfen son cevabı $\\boxed{}$ içine yazın.",
    "pl": "Uwaga: Proszę umieścić końcową odpowiedź w $\\boxed{}$.",
    "uk": "Примітка: Будь ласка, помістіть остаточну відповідь у $\\boxed{}$.",
    "uz": "Eslatma: Iltimos, yakuniy javobni $\\boxed{}$ ichiga yozing.",
    "or": "ଟିପ୍ପଣୀ: ଦୟାକରି ଶେଷ ଉତ୍ତରକୁ $\\boxed{}$ ଭିତରେ ରଖନ୍ତୁ।",
    "am": "ማስታወሻ፡ እባክዎ የመጨረሻውን መልስ በ$\\boxed{}$ ውስጥ ያስገቡ።",
    "el": "Σημείωση: Παρακαλώ βάλτε την τελική απάντηση μέσα στο $\\boxed{}$.",
    "kk": "Ескерту: Соңғы жауапты $\\boxed{}$ ішіне жазыңыз.",
    "cs": "Poznámka: Prosím vložte konečnou odpověď do $\\boxed{}$.",
    "he": "הערה: נא לשים את התשובה הסופית בתוך $\\boxed{}$.",
    "sr": "Напомена: Молимо ставите коначан одговор у $\\boxed{}$.",
    "tt": "Искәрмә: Зинһар, соңгы җавапны $\\boxed{}$ эченә куегыз.",
    "sk": "Poznámka: Prosím vložte konečnú odpoveď do $\\boxed{}$.",
    "ca": "Nota: Si us plau, poseu la resposta final dins de $\\boxed{}$.",
    "cv": "Асӑрхаттару: Юлашки хуравăрăн $\\boxed{}$ ӑшне лартăр.",
    "hsb": "Kedźbu: Prošu stajće kónčnu wotmołwu do $\\boxed{}$.",
    "dsb": "Glědajśo: Pšosym stajśo kóńcnu wótegrono do $\\boxed{}$.",
}
